### PR TITLE
Made csv header reader a little bit more flexable and up-to-date with…

### PR DESCRIPTION
**Pull request by SRGDamia1**
… ModularSensors library

I do not have the site set up locally for any testing myself, so I haven't actually tested this.

### CODE REVIEW

**Comment by aufdenkampe** [comment]
@jcaraballo17, let us know if you need more info to test this. We definitely want this for the current milestone.
cc: @horsburgh

**Comment by aufdenkampe** [comment]
BTW, if you switch to using the Pandas library, this PR might not be useful.

**Comment by SRGDamia1** [comment]
Unless pandas will be in 0.9.5, please put this in.

**Comment by horsburgh** [comment]
@jcaraballo17 is testing this now. Our plan is to push a fix for the CSV download with this next release and so we are considering this code for this release. Rearchitecting to use Pandas has been moved to the next release.

**Comment by SRGDamia1** [comment]
Great, thanks!

**Comment by jcaraballo17** [comment]
@SRGDamia1 I tested this with some old files and also modified them myself so they have a row with the Result UUIDs like the new files. Everything works great, but I'll need test it with an actual CSV generated by the logger.  Can you upload one to Google Drive? I just need to make sure it matches what I did with the old ones.

**Comment by jcaraballo17** [comment]
Merging. We can test both file formats in the sandbox.

**Comment by aufdenkampe** [comment]
I'm interested to hear if this passes testing.

**Comment by SRGDamia1** [comment]
It worked for me uploading a new file with a slightly different format.

**Pull request merged**
