### PR TITLE
Release 0.12.1 Hotfixes

### PR DESCRIPTION
**Pull request by aufdenkampe**
Merging a number of hHotfixes & Tweaks to AWS release, as described 
https://github.com/ODM2/ODM2DataSharingPortal/milestone/23?closed=1

For some additional details, see:
- #539
- #541
- #547

### CODE REVIEW

**Comment by neilh10** [comment]
Would it be OK to try out some fast testing "30msgs/hour"  against this - possibly this weekend?

**Comment by aufdenkampe** [comment]
@neilh10, go for it. Just let @ptomasula, @htaolimno, and I know what period you send those extra messages and we can show you the CPU and other AWS metrics. 

We would also love to see what kind of response times you get.

**Comment by neilh10** [comment]
Hi @aufdenkampe ,  @ptomasula, @htaolimno,  
I started a test yesterday 
2022-01-07 19:23:46.790 PST  
Its using the Mayfly 1.0A3 (first time for testing) taking a sample every  2minutes and POSTING it - over WiFi - locally I've got a comcast upload 6MB download 60MB.

Good news, after some 20hours the responses are 201's, and with an adequate response time, mostly about 3.2Seconds but an interesting occasional very fast ~360-440mS
See attached. 
[response220108_1538.txt](https://github.com/ODM2/ODM2DataSharingPortal/files/7834218/response220108_1538.txt)

Its a development build, primarily checking a new type of runtime instantiation of the Modem (class loggerModem) - regression testing on the Mayfly 1.0, as well as the server response.
After this weekend, when the code is tidied up I'll use the same .hex for running off Mayfly with Digi LTE

**Comment by aufdenkampe** [comment]
@neilh10, thanks for letting us know that response codes and times are looking much better on your end! Yay!

My quick scan is that your test does not show any impact on DB server CPU usage, suggesting that your high frequency tests are easily handled amidst other traffic.

This suggests that our hot fix worked!

**Pull request merged**
